### PR TITLE
update db schema and test data

### PR DESCRIPTION
**Pull request by Kevin1289**
Update schema to have needed data for all pages

### CODE REVIEW

**Review by bls1999 — CHANGES_REQUESTED** [review]
I'm not sure why we now have a separate file for the schema. My instructions in `db.js` were explicit in saying the schema goes in `db.js`, and I was under the impression that we were all on the same page. Did this change?

Additionally, inserting test data every time we connect is not needed. We should be able to do it once from an insert script.

**Review by shaygyawali — APPROVED** [review]

**Comment by Kevin1289** [comment]
> p

I decided that it would be nice to have the schema in a different file to keep things organized. Should not affect functionality. The insert is not happening every time. I make sure to check that the data is missing before inserting. I'm doing this just incase a row gets deleted, so we don't need to manually insert data again. This also should not affect functionality.

**Comment by bls1999** [comment]
> I decided that it would be nice to have the schema in a different file to keep things organized. Should not affect functionality. The insert is not happening every time. I make sure to check that the data is missing before inserting. I'm doing this just incase a row gets deleted, so we don't need to manually insert data again. This also should not affect functionality.  
> 
> 
> 
> This merge is critical so that other database work can follow. Let's not focus on formatting issues.

We will discuss at the meeting tonight.

**Review by bls1999 — APPROVED** [review]
After review during a daily standup, the group collectively verbally agreed to change the design standards to the method used in the pull.

**Pull request merged**
